version: '3'

services:
  db:
    image: postgres
  web:
    build: .
    command: python3 manage.py runserver_plus 0.0.0.0:8000
    volumes:
      - .:/dj_shop
    ports:
      - "8000:8000"
    depends_on:
      - db